// This file was auto-generated by ML.NET Model Builder. 

using System;
using Mobile_price_classificationML.Model;

namespace Mobile_price_classificationML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Battery_power = 842F,
                Clock_speed = 2.2F,
                Dual_sim = @"0",
                Int_memory = 7F,
                N_cores = 2F,
                Px_height = 20F,
                Px_width = 756F,
                Ram = 2549F,
                Touch_screen = @"0",
                Wifi = @"1",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price_range with predicted Price_range from sample data...\n\n");
            Console.WriteLine($"Battery_power: {sampleData.Battery_power}");
            Console.WriteLine($"Clock_speed: {sampleData.Clock_speed}");
            Console.WriteLine($"Dual_sim: {sampleData.Dual_sim}");
            Console.WriteLine($"Int_memory: {sampleData.Int_memory}");
            Console.WriteLine($"N_cores: {sampleData.N_cores}");
            Console.WriteLine($"Px_height: {sampleData.Px_height}");
            Console.WriteLine($"Px_width: {sampleData.Px_width}");
            Console.WriteLine($"Ram: {sampleData.Ram}");
            Console.WriteLine($"Touch_screen: {sampleData.Touch_screen}");
            Console.WriteLine($"Wifi: {sampleData.Wifi}");
            Console.WriteLine($"\n\nPredicted Price_range value {predictionResult.Prediction} \nPredicted Price_range scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
