// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Mobile_price_classificationML.Model
{
    public class ModelInput
    {
        [ColumnName("battery_power"), LoadColumn(0)]
        public float Battery_power { get; set; }


        [ColumnName("clock_speed"), LoadColumn(1)]
        public float Clock_speed { get; set; }


        [ColumnName("dual_sim"), LoadColumn(2)]
        public string Dual_sim { get; set; }


        [ColumnName("int_memory"), LoadColumn(3)]
        public float Int_memory { get; set; }


        [ColumnName("n_cores"), LoadColumn(4)]
        public float N_cores { get; set; }


        [ColumnName("px_height"), LoadColumn(5)]
        public float Px_height { get; set; }


        [ColumnName("px_width"), LoadColumn(6)]
        public float Px_width { get; set; }


        [ColumnName("ram"), LoadColumn(7)]
        public float Ram { get; set; }


        [ColumnName("touch_screen"), LoadColumn(8)]
        public string Touch_screen { get; set; }


        [ColumnName("wifi"), LoadColumn(9)]
        public string Wifi { get; set; }


        [ColumnName("price_range"), LoadColumn(10)]
        public float Price_range { get; set; }


    }
}
